[colors.primary]
background = "#282828"
foreground = "#d4be98"
bright_foreground = "#d4be98"

[colors.normal]
black = "#3c3836"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.bright]
black = "#7c6f64"
red = "#ea6962"
green = "#a9b665"
yellow = "#d8a657"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#d4be98"

[colors.cursor]
cursor = "#d4be98"
text = "#282828"

[colors.footer_bar]
background = "#282828"
foreground = "#d4be98"

[colors.hints.end]
background = "#282828"
foreground = "#d8a657"

[colors.hints.start]
background = "#d8a657"
foreground = "#282828"

[colors.search.focused_match]
background = "#e78a4e"
foreground = "#282828"

[colors.search.matches]
background = "#45403d"
foreground = "#282828"

[colors.selection]
background = "#3c3836"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Curlio"
style = "Bold"

[font.bold_italic]
family = "Curlio"
style = "Bold Italic"

[font.italic]
family = "Curlio"
style = "Italic"

[font.normal]
family = "Curlio"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.padding]
x = 5
y = 5

[general]
ipc_socket = false
live_config_reload = false
