format = '$directory$shlvl$character'
right_format = '$status$cmd_duration$jobs$all'
scan_timeout = 30
command_timeout = 500
add_newline = false

# Builtin
[battery]
format = '[$percentage]($style) '

[character]
format = '$symbol '
success_symbol = "[\uf0da](green)" # nf-fa-caret-right
error_symbol = "[\uf0da](red)"     # nf-fa-caret-right
vimcmd_symbol = '[N](green)'

[cmd_duration]
format = '[$duration]($style) '
min_time = 10_000
# show_notifications = true
# min_time_to_notify = 60_000
style = 'bright-black'

# [custom]
# disabled = true

[directory]
truncation_length = 5
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = ' ro'
style = 'white'
fish_style_pwd_dir_length = 1

# [env_var]
# disabled = true

[fill]
symbol = ' ' # ─ ━

[hostname]
# ssh_only = false
# format = '[$hostname]($style)\] '
# style = 'yellow'
disabled = true

[jobs]
style = 'bright-black'

[line_break]
disabled = true

[localip]
disabled = true

[memory_usage]
# format = '\[$symbol[$ram( | $swap)]($style)\] '
# style = 'white'
disabled = true

[os]
disabled = true

[package]
# format = '\[[$symbol$version]($style)\] '
# version_format = '${raw}'
# symbol = ''
# style = '214'
# display_private = true
disabled = true

[shell]
disabled = true

[shlvl]
threshold = 3
format = '[$shlvl]($style) '
style = 'yellow'
disabled = false

[status]
format = '[$symbol$status]($style) '
symbol = ''
style = 'red'
disabled = false

[time]
# format = '[$time]($style) '
# time_format = '%R'
# style = 'white'
disabled = true

[username]
# style_root = 'red'
# style_user = 'yellow'
# format = '\[[$user]($style)@'
# show_always = true
disabled = true

# VCS
[fossil_branch]
disabled = true
[fossil_metrics]
disabled = true
[hg_branch]
disabled = true
[pijul_channel]
disabled = true
[vcsh]
disabled = true

[git_branch]
format = '([$symbol$branch]($style) )'
symbol = ''                            # 
style = 'green'

[git_commit]
commit_hash_length = 7
format = '[$hash$tag]($style) '
style = 'white'
only_detached = false

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = 'yellow'

[git_metrics]
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = 'green'
deleted_style = 'red'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = '>'
behind = '<'
diverged = '<>'
renamed = 'r'
deleted = 'x'
style = 'red'

# Environments
[aws]
disabled = true
[azure]
disabled = true
[buf]
disabled = true
[bun]
disabled = true
[c]
disabled = true
[cmake]
disabled = true
[cobol]
disabled = true
[conda]
disabled = true
[container]
symbol = "\uf4b7" # nerd icon nf-oct-container
[crystal]
disabled = true
[daml]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[direnv]
format = '[$symbol]($style)'
symbol = "\uf07b"
style = 'blue'
allowed_msg = 'a'
denied_msg = 'd'
loaded_msg = 'l'
unloaded_msg = 'u'
disabled = false
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[fennel]
disabled = true
[gcloud]
disabled = true
[golang]
disabled = true
[gradle]
disabled = true
[guix_shell]
disabled = true
[haskell]
disabled = true
[haxe]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[kubernetes]
disabled = true
[lua]
disabled = true
[meson]
disabled = true
[nim]
disabled = true
[nix_shell]
format = '[$symbol]($style)'
symbol = "\uf313"            # nf-linux-nixos
style = 'cyan'
impure_msg = 'i'
pure_msg = 'p'
disabled = false
[nodejs]
disabled = true
[ocaml]
disabled = true
[opa]
disabled = true
[openstack]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[raku]
disabled = true
[red]
disabled = true
[rlang]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[singularity]
disabled = true
[solidity]
disabled = true
[spack]
disabled = true
[sudo]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[typst]
disabled = true
[vagrant]
disabled = true
[vlang]
disabled = true
[zig]
disabled = true
