#!/usr/bin/env zsh

gh repo clone hlissner/doom-emacs ~/.config/emacs -- --depth 1

brew tap d12frosted/emacs-plus
brew install emacs-plus@28 \
    --with-xwidgets \
    --with-imagemagick \
    --with-native-comp \
    --with-modern-doom3-icon \

ln -sf ${HOMEBREW_PREFIX}/opt/emacs-mac/Emacs.app /Applications
brew services restart emacs-plus@28

~/.config/emacs/bin/doom install
