#!/usr/bin/env bash
# Set global git options.

declare -r red='\033[31m' # foreground red
declare -r nt='\033[0m'   # normal text

# check if git is installed
check_git() {
  if [[ ! -x "$(command -v git)" ]]; then
    err_msg 'This script requires git' 1
  fi
}

# setup git
setup_git() {
  git config --global core.autocrlf     false
  git config --global core.eol          'lf'
  if [[ -x "$(command -v nvim)" ]]; then
    git config --global core.editor     'nvim'
  else
    git config --global core.editor     'vim'
  fi
  git config --global user.name         'Teddy Byron'
  git config --global user.email        'ted@tedbyron.com'
  if [[ -n "$1" ]]; then
    git config --global user.signingkey "$1"
  fi
  git config --global commit.gpgsign    true
  git config --global tag.gpgsign       true
}

err_msg() {
  echo -e "${red}ERR${nt}: $1." >&2
  if (($# > 1)); then
    exit 1
  fi
}

main() {
  local -i exit_code=0
  set -E
  trap '(( exit_code++ ))' ERR

  check_git

  case "$#" in
    0|1) setup_git "$@";;
    *) err_msg "$0 requires 1 argument: user.signingkey" 1 ;;
  esac

  exit "${exit_code}"
}

main "$@"
