#!/usr/bin/env zsh

declare -r red='\033[31m'
declare -r nt='\033[0m'

check_git() {
  if [[ ! -x "$(command -v git)" ]]; then
    err_msg 'This script requires git' 1
  fi
}

setup_git() {
  git config --global core.autocrlf       false
  git config --global core.eol            'lf'
  if [[ -x "$(command -v nvim)" ]]; then
    git config --global core.editor       'nvim'
  else
    git config --global core.editor       'vim'
  fi
  git config --global user.name           'Teddy Byron'
  git config --global user.email          'ted@tedbyron.com'
  if [[ -n "$1" ]]; then
    git config --global user.signingkey   "$1"
  fi
  git config --global commit.gpgSign      true
  git config --global tag.gpgSign         true
  git config --global init.defaultBranch  'main'
}

err_msg() {
  echo -e "${red}ERR${nt}: $1." >&2
  if (($# > 1)); then
    exit 1
  fi
}

main() {
  local -i exit_code=0
  set -E
  trap '(( exit_code++ ))' ERR

  check_git

  case "$#" in
    0|1) setup_git "$@";;
    *) err_msg "$0 requires 1 argument: user.signingkey" 1 ;;
  esac

  exit "${exit_code}"
}

main "$@"
