-- https://github.com/williamboman/mason-lspconfig.nvim/blob/main/doc/server-mapping.md

local not_vscode = not vim.g.vscode

return {
  {
    'nvim-lspconfig',
    enabled = not_vscode,
    opts = {
      servers = {
        bashls = {},
        bright_script = {},
        cssls = {},
        -- docker_compose_language_service = {},
        -- dockerls = {},
        -- elixirls = {},
        emmet_ls = {},
        html = {},
        -- prismals = {},
        rnix = {},
        rust_analyzer = {},
        svelte = {},
        tailwindcss = {},
        taplo = {},
        volar = {},
      },
    },
  },
  { 'neoconf.nvim', enabled = not_vscode },
  { 'neodev.nvim', enabled = not_vscode },
  { 'mason-lspconfig.nvim', enabled = not_vscode },
  { 'cmp-nvim-lsp', enabled = not_vscode },
  { 'null-ls.nvim', enabled = not_vscode },
  {
    'mason.nvim',
    enabled = not_vscode,
    opts = {
      ensure_installed = {
        'actionlint',
        'bash-language-server',
        'brighterscript',
        'brighterscript-formatter',
        'bslint',
        -- 'codelldb',
        'css-lsp',
        -- 'docker-compose-language-service',
        -- 'dockerfile-language-server',
        -- 'elixir-ls',
        'emmet-ls',
        'eslint_d',
        'html-lsp',
        -- 'prisma-language-server',
        'rnix-lsp',
        'rust-analyzer',
        'shellcheck',
        'shfmt',
        'stylua',
        'svelte-language-server',
        'tailwindcss-language-server',
        'taplo',
        'vue-language-server',
      },
    },
  },
}
