return {
  {
    'nvim-treesitter',
    opts = {
      ensure_installed = {
        'bash',
        'css',
        'csv',
        'diff',
        -- 'dockerfile',
        'elixir',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'hjson',
        'html',
        'ini',
        'javascript',
        'jsdoc',
        'json',
        'json5',
        'jsonc',
        -- 'linkerscript',
        'lua',
        'luadoc',
        'luap',
        'markdown',
        'markdown_inline',
        'nix',
        -- 'prisma',
        'query',
        'regex',
        'rust',
        'sql',
        'svelte',
        'toml',
        'tsx',
        'typescript',
        'vimdoc',
        'vue',
        'yaml',
      },
    },
  },
}
