import = ["/Users/ted/.config/alacritty/colors.toml"]

[env]
TERM = "alacritty"

[font]
size = 14.0
normal = { family = "Curlio", style = "Regular" }
bold = { family = "Curlio", style = "Bold" }
italic = { family = "Curlio", style = "Italic" }
bold_italic = { family = "Curlio", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"
title = "Alacritty"
padding = { x = 5, y = 5 }
