[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

[colors.footer_bar]
background = "#282828"
foreground = "#ebdbb2"

[colors.hints.end]
background = "#282828"
foreground = "#d79921"

[colors.hints.start]
background = "#d79921"
foreground = "#282828"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#282828"
bright_foreground = "#fbf1c7"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#d65d0e"
foreground = "#3c3836"

[colors.search.matches]
background = "#689d6a"
foreground = "#3c3836"

[colors.selection]
background = "#3c3836"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "Curlio"
style = "Bold"

[font.bold_italic]
family = "Curlio"
style = "Bold Italic"

[font.italic]
family = "Curlio"
style = "Italic"

[font.normal]
family = "Curlio"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.padding]
x = 5
y = 5

[general]
ipc_socket = false
live_config_reload = false
