[buildPlans.curlio]
family = "Curlio"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

webfont-formats = ['ttf', 'woff2']

[buildPlans.curlio.variants]
inherits = "ss20"

[buildPlans.curlio.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-flat-hook-serifless"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-flat-tailed"
t = "flat-hook"
u = "toothed-serifless"
y = "curly-turn-serifless"

long-s = "bent-hook-serifless"
eszet = "sulzbacher-serifless"

lower-iota = "serifed-flat-tailed"
lower-tau = "flat-tailed"

cyrl-u = "curly-serifless"
cyrl-ef = "serifless"
cyrl-yeri = "corner"
cyrl-yery = "corner"

zero = "long-dotted"
four = "closed"
five = "upright-flat"
seven = "curly-serifless"

asterisk = "penta-low"
brace = "straight"
guillemet = "straight"
at = "fourfold-solid-inner"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
lig-neq = "vertical"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.curlio.ligations]
inherits = "javascript"
enables = ["arrow-l", "hash-hash"]

[buildPlans.curlio.widths.condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.curlio.widths.normal]
shape = 600
menu = 5
css = "normal"
